# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # General provision scripts
  config.ssh.insert_key = false

  ##############################################################################
  # PUPETMASTER CONFIG
  #
  config.vm.define "master" do |master|
    # Vagrant box flavor and repo
    #master.vm.box = "centos/7"
    #master.vm.box_url = "https://atlas.hashicorp.com/centos/boxes/7"
    master.vm.box = "geerlingguy/centos7"
    master.vm.box_url = "https://atlas.hashicorp.com/geerlingguy/boxes/centos7"

    master.vm.hostname =  "master.puppet.local"
    master.vm.network "private_network", ip: "192.168.33.100"

    # Map internal ports services
    # puppetmaster dashboard
    master.vm.network "forwarded_port", guest: 8080, host: 18080, host_ip: '127.0.0.1', auto_correct: true
    # CouchDB web interface
    master.vm.network "forwarded_port", guest: 5984, host: 15984, host_ip: '127.0.0.1', auto_correct: true

    # mount folders
    master.vm.synced_folder "../modules", "/etc/puppetlabs/code/environments/production/modules"
    master.vm.synced_folder "../manifests", "/etc/puppetlabs/code/environments/production/manifests"
    master.vm.synced_folder "../hieradata", "/etc/puppetlabs/code/environments/production/hieradata"

    master.vm.provider "virtualbox" do |v|
      v.name    = "master.puppet.local"
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.memory = "3072"
      v.cpus = 2
    end

    # Puppet master provision script
    master.vm.provision "shell", path: "./scripts/bootstrap-redhat-family.sh"
    master.vm.provision "shell", path: "./scripts/provision-postgresql.sh"
    master.vm.provision "shell", path: "./scripts/provision-couchdb.sh"
    master.vm.provision "shell", path: "./scripts/provision-puppetserver.sh"
    master.vm.provision "shell", path: "./scripts/provision-puppetdb.sh"
    master.vm.provision "shell", path: "./scripts/configure-puppet.sh"
    master.vm.provision "shell", path: "./scripts/configure-puppetdb-ssl.sh"
    master.vm.provision "shell", path: "./scripts/enable-manifest-for-vagrant-nodes.sh"
    master.vm.provision "shell", path: "./scripts/provision-vbox-additions.sh"
  end

  ##############################################################################
  # AGENTS' CONFIG
  config.vm.define "agent-01" do |agent01|
    # Vagrant box flavor and repo
    agent01.vm.box = "geerlingguy/centos7"
    agent01.vm.box_url = "https://atlas.hashicorp.com/geerlingguy/boxes/centos7"

    agent01.vm.hostname =  "agent-01.puppet.local"
    agent01.vm.network "private_network", ip: "192.168.33.101"

    agent01.vm.provider "virtualbox" do |v|
      v.name    = "agent-01.puppet.local"
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.memory = "1024"
      v.cpus = 1
    end

    # Puppet agent provision script
    agent01.vm.provision "shell", path: "./scripts/bootstrap-redhat-family.sh"
    agent01.vm.provision "shell", path: "./scripts/provision-agent-redhat-family.sh"
    agent01.vm.provision "shell", path: "./scripts/provision-vbox-additions.sh"
  end

  config.vm.define "agent-02" do |agent02|
    # Vagrant box flavor and repo
    agent02.vm.box = "ubuntu/trusty64"
    agent02.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"

    agent02.vm.hostname =  "agent-02.puppet.local"
    agent02.vm.network "private_network", ip: "192.168.33.102"

    agent02.vm.provider "virtualbox" do |v|
      v.name    = "agent-02.puppet.local"
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.memory = "1024"
      v.cpus = 1
    end

    # Puppet agent provision script
    agent02.vm.provision "shell", path: "./scripts/bootstrap-debian-family.sh"
    agent02.vm.provision "shell", path: "./scripts/provision-agent-debian-family.sh"
    agent02.vm.provision "shell", path: "./scripts/provision-vbox-additions.sh"
  end
end
